### ISSUE TITLE
caminho para arquivo hardcoded

### ISSUE THREAD

**Issue by Nipodemos** [edwss/openkoreControl#1]
oi! amei essa função de olhar pelo telegram! muito top, mas não usei ainda

aqui, tenho uma dúvida, esses caminhos estão todos escritos de forma que não podem ser diferentes, oq acontece no pc de outras pessoas?
https://github.com/edwss/openkoreControl/blob/768d513694f32fa5d4f5e51764bcaf97c0f64c34/plugin/botControl.pl#L26

https://github.com/edwss/openkoreControl/blob/768d513694f32fa5d4f5e51764bcaf97c0f64c34/plugin/botControl.pl#L36

https://github.com/edwss/openkoreControl/blob/768d513694f32fa5d4f5e51764bcaf97c0f64c34/plugin/botControl.pl#L41

https://github.com/edwss/openkoreControl/blob/768d513694f32fa5d4f5e51764bcaf97c0f64c34/plugin/botControl.pl#L51

**Comment by edwss** [comment]
Tu respondeu a pergunta na propria pergunta, eu nao fiz ele ser "dinamico" porque a ideia nao era lancar a publico. Entao se tu quiser usar vai ter que mudar esse caminho para o arquivo.

**Comment by Nipodemos** [comment]
okay, obrigado 😄
